#Construct an employee class
#emp id to be auto generated by EmployeeManager class to prevent duplication
#same for discount number. Will be auto generated by Manager
class Employee:
    def __init__(self,name,emp_type,years_worked):
        self.id = 0
        self.name = name
        self.emp_type = emp_type
        self.years_worked = years_worked
        self.emp_disc_num = 0
        self.total_purchased = 0
        self.total_discounts = 0
        self.employee_discount = self.calculate_discount() #this works
    
    def calculate_discount(self):
        if(self.emp_type == "hourly"):

            if(self.years_worked >= 5):
                return 0.10
            
            return 0.02 * self.years_worked
        
        if(self.emp_type == "manager"):
            if(self.years_worked >= 5):
                return 0.20 
            
            return (0.02 * self.years_worked) + 0.10
        
        
    #individual object print so I can simply loop over the list to print all employees
    def print_employee(self):
        s = str(self.id) + ", " + str(self.name) + ", " + str(self.emp_type) + ", " + str(self.years_worked) 
        s += ", " + str(self.total_purchased) + ", " + str(self.total_discounts) + ", " + str(self.emp_disc_num) + "\n"
        return s